Morax product details
arfa/commerce pull request #175
Opened 2022-07-14 16:29 UTC by wassim-arfa

2022-07-15 14:10 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +        <>
maybe `<Stack />` to handle mobile use case

2022-07-15 14:12 UTC, arfa commented on packages/chakraui/src/components/common/Share/Share.tsx
> +          <ShareButton aria-label="Share with Mail">
you must specify a key

2022-07-15 14:13 UTC, arfa requested changes
⚠️  resolve conflict

2022-07-15 16:00 UTC, wassim-arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +                        defaultValue={option.values[0].label}
```jsx
defaultValue?: StringOrNumber
```
```ts
type StringOrNumber = string | number;
```

2022-07-18 01:56 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +                        defaultValue={option.values[0].label}
```jsx 
defaultValue={option.values[0].value}
```
same result, not the same meaning => respect the meaning and  web standard

2022-07-21 17:29 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +                        defaultValue={option.values[0].label}
defaultValue={option.values[0].hexColors}

2022-07-21 17:29 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +                        defaultValue={option.values[0].label}
idem

2022-07-25 19:54 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
```jsx
export function ProductOptions({ product, stackProps }: Props) {
  return (
    <Stack {...stackProps}>
      {product.options?.map((option) => {
        const Comp = option.displayName.toLocaleLowerCase() === 'color' ? ColorPicker : SizePicker;
        return (
          <Stack flex="1">
            <Comp
              label={option.displayName}
              defaultValue={option.values[0].value}
              options={option.values}
            />
          </Stack>
        );
      })}
    </Stack>
  );
}

2022-07-25 19:54 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
un pattern à garder en tête

2022-07-25 19:56 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
regarde dans le code que t'as écrit,
il y a une répétition, 
un pattern qui se répète,
les deux composant ont la même interface (props),

2022-07-25 19:57 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
c'est pour cette raison c'est important de  créer une coherence dans le code,
on a besoin de ce genre de répétition...

2022-07-25 20:04 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
**dans un 2ème temps** 
on peut penser à un seul composant `Picker` 
qui combine les deux composants,
avec une prop supplémentaire `type = 'color' | 'size'`

2022-07-25 20:07 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
`ProductOptions` peut faire ce travail aussi en ajoutant une prop `type = 'color' | 'size'`

2022-07-25 20:10 UTC, arfa commented on packages/chakraui/src/components/common/ProductQuickShop/ProductOptions.tsx
> +}
```jsx
const mapTypeToComponent = {
  color: ColorPicker,
  size: SizePicker,
};

export function ProductOptions({ product, stackProps }: Props) {
  return (
    <Stack {...stackProps}>
      {product.options?.map((option) => {
        const Comp = mapTypeToComponent[option.displayName.toLocaleLowerCase()];
        return (
          <Stack flex="1">
            <Comp
              label={option.displayName}
              defaultValue={option.values[0].value}
              options={option.values}
            />
          </Stack>
        );
      })}
    </Stack>
  );
}

2022-07-26 10:08 UTC, merged